version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  server:
    image: server
    build:
      context: ./server/

    stdin_open: true
    ports:
      - "5000:5000"
    depends_on:
      - broker
    env_file:
      - ./server/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  producer:
    image: producer
    build:
      context: ./data-producer/
    stdin_open: true
    depends_on:
      - broker
      - server
    env_file:
      - ./data-producer/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  client:
    image: client
    build:
      context: ./client/
      target: production
      args:
        NODE_VERSION: 19
    stdin_open: true
    ports:
      - "8080:80"
    links:
      - server
    depends_on:
      - server
      - producer
    env_file:
      - ./client/.env

  init-kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - broker
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server broker:9092 --create --if-not-exists --topic events
      "
